[package]
name = "practice"
version = "0.1.0"
authors = ["yukihir0 <yukihiro.cotori@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "0.4.1"

[profile.release]
lto = true
panic = 'abort'
